[project]
name = "media_only_tg_bot"
version = "1.0.0"
description = "A script for a Telegram bot that deletes non-photo material from a group chat topic."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic[email]>=2.9.2",
    "pydantic-settings>=2.6.1",
    "python-telegram-bot>=21.7",
]
[project.optional-dependencies]
dev = [
    "ruff>=0.7.3",
    "pylint>=3.3.1", # For now - https://github.com/astral-sh/ruff/issues/970
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "pytest-mypy-plugins>=3.1.2",
    "tox>=4.23.2",
    "tox-uv>=1.16.0",
]
[tool.mypy]
plugins = ['pydantic.mypy']
[tool.ruff]
line-length = 100