[project]
name = "media_only_tg_bot"
version = "1.0.0"
description = "A script for a Telegram bot that deletes non-photo material from a group chat topic."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic-settings>=2.6.1",
    "python-telegram-bot>=21.7",
]
[project.optional-dependencies]
dev = [
    "ruff>=0.7.3",
    # For now - https://github.com/astral-sh/ruff/issues/970
    "pylint>=3.3.1",
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
]