name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system ".[test]"
          uv pip install --system tox tox-uv

      - name: Run tests with tox-uv
        run: tox -e py312

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Tox directory contents:"
          ls -la .tox || echo "No .tox directory"
          echo "Searching for coverage.xml:"
          find . -name coverage.xml

      - name: Move coverage file
        run: |
          if [ -f ".tox/py312/coverage.xml" ]; then
            cp .tox/py312/coverage.xml ./coverage.xml
          elif [ -f ".coverage" ]; then
            python -m coverage xml
          else
            echo "No coverage file found"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true